name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Determine compose-runner version
        id: get_version
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "branch" ]]; then
            VERSION="${GITHUB_SHA::12}"
          elif [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VERSION="${GITHUB_REF_NAME}"
          elif [[ "${GITHUB_REF_TYPE}" == "release" ]]; then
            VERSION="${GITHUB_REF_NAME}"
          else
            VERSION="${GITHUB_SHA::12}"
          fi
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            COMPOSE_RUNNER_VERSION=${{ steps.get_version.outputs.version }}
          tags: |
            ghcr.io/neurostuff/nsc-runner:${{ steps.get_version.outputs.version }}
            ghcr.io/neurostuff/nsc-runner:${{ github.ref_name == 'main' && 'latest' || steps.get_version.outputs.version }}
